Install scripts still broken, but I found problem.
- I eliminated df_home variable, but sourced scripts still used it
- May need to unwind a few things looking for the problem

diff --git a/bin/bashInstall b/bin/bashInstall
--- a/bin/bashInstall
+++ b/bin/bashInstall
@@ -10,76 +10,81 @@
 #              --remove:  removes files which were installed
 #              --clean:   same as above, deletes emptied directories
 #              --nuke:    same as above but cleans up other content
-#
-# shellcheck shell=dash
-#
+
+# shellcheck shell=sh
+
+export SCRIPT_NAME=bashInstall
+export DF_ACTION=install
 
 export DOTFILES_GIT_REPO="${DOTFILES_GIT_REPO:=$HOME/devel/dotfiles}"
-: "${df_home:=$DOTFILES_GIT_REPO/home}"
-: "${script_name:=bashInstall}"
+cd "$DOTFILES_GIT_REPO/home" || {
+    printf 'bashInstall: failed to cd into %s\n' "$DOTFILES_GIT_REPO/home" >&2
+    exit 1
+}
 
-cd "$df_home" || { printf '%s: failed to cd into %s\n' "$script_name" "$df_home"; }
+umask 0022
 
-. ../bin/sourced/setup.sh
+. ../bin/sourced/parse_cmdline.sh
+. ../bin/sourced/functions.sh
 
 bash_files='
-   .bash_logout
-   .bash_profile
-   .bashrc
-   .inputrc
+    .bash_logout
+    .bash_profile
+    .bashrc
+    .inputrc
 '
 
 bin_scripts='
-   chkcolor
-   codepoint
-   etherApe
-   monitor
-   myCalc
-   pathtrim
-   rt
-   spin
-   viewJarManifest
+    chkcolor
+    codepoint
+    etherApe
+    monitor
+    myCalc
+    pathtrim
+    rt
+    spin
+    viewJarManifest
 '
 
 remove_items="
-   $HOME/.bash_login
-   $HOME/.profile
+    $HOME/.bash_login
+    $HOME/.profile
 "
 
 dirs_to_create="
-   $HOME/catch
-   $HOME/.local/bin
+    $HOME/catch
+    $HOME/.local/bin
 "
 
 items_to_clean="
-   $HOME/.bash_history
+    $HOME/.bash_history
 "
 
 items_to_nuke="
-   $HOME/catch
+    $HOME/catch
 "
 
 ## Perform ACTION
 
 case "$DF_ACTION" in
-   install|check|remove)
-      # Process bash config files
-      process_files "$HOME" "$bash_files" . 0644
-
-      # Process ~/bin scripts
-      process_files "$HOME/bin" "$bin_scripts" bin 0755
-      chmod 0755 "$HOME/bin"
-
-      # Remove/report no longer needed files and directories
-      remove_items "$remove_items"
-
-      # Create/report missing/delete directories
-      ensure_dirs "$dirs_to_create"
-      ;;
-   clean)
-      remove_items "$items_to_clean"
-      ;;
-   nuke)
-      remove_items "$items_to_clean $items_to_nuke"
-      ;;
+    install|check|remove)
+        # Process bash config files
+        process_files "$HOME" "$bash_files" . 0644
+ 
+        # Process ~/bin scripts
+        process_files "$HOME/bin" "$bin_scripts" bin 0755
+        chmod 0755 "$HOME/bin"
+ 
+        # Remove/report no longer needed files and directories
+        remove_items "$remove_items"
+ 
+        # Create/report missing/delete directories
+        ensure_dirs "$dirs_to_create"
+        ;;
+    clean)
+        remove_items "$items_to_clean"
+        ;;
+    nuke)
+        remove_items "$items_to_clean $items_to_nuke"
+        ;;
 esac
diff --git a/bin/develInstall b/bin/develInstall
--- a/bin/develInstall
+++ b/bin/develInstall
@@ -10,75 +10,96 @@
 #              --remove:  removes files which were installed
 #              --clean:   same as above, deletes emptied directories
 #              --nuke:    same as above but cleans up other content
-#
-# shellcheck shell=dash
-#
+
+# shellcheck shell=sh
+
+export SCRIPT_NAME=develInstall
+export DF_ACTION=install
 
 export DOTFILES_GIT_REPO="${DOTFILES_GIT_REPO:=$HOME/devel/dotfiles}"
-: "${df_home:=$DOTFILES_GIT_REPO/home}"
-: "${script_name:=develInstall}"
+cd "$DOTFILES_GIT_REPO/home" || {
+    printf 'develInstall: failed to cd into %s\n' "$DOTFILES_GIT_REPO/home" >&2
+    exit 1
+}
 
-cd "$df_home" || { printf '%s: failed to cd into %s\n' "$script_name" "$df_home"; }
+umask 0022
 
-. ../bin/sourced/setup.sh
+. ../bin/sourced/parse_cmdline.sh
+. ../bin/sourced/functions.sh
+
+# Script exclusively use these names
+export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:=$HOME/.config}"
+export XDG_CACHE_HOME="${XDG_CACHE_HOME:=$HOME/.cache}"
+export XDG_DATA_HOME="${XDG_DATA_HOME:=$HOME/.local/share}"
+export XDG_STATE_HOME="${XDG_STATE_HOME:=$HOME/.local/state}"
+
+# Ensure these folder exists before installation.
+ensure_dir "$XDG_CONFIG_HOME"
+chmod 0755 "$XDG_CONFIG_HOME"
+ensure_dir "$XDG_DATA_HOME"
+chmod 0755 "$XDG_DATA_HOME"
+ensure_dir "$XDG_STATE_HOME"
+chmod 0755 "$XDG_STATE_HOME"
+ensure_dir "$XDG_CACHE_HOME"
+chmod 0755 "$XDG_CACHE_HOME"
 
 cabal_files='
-   config
+    config
 '
 
 dot_config_files='
-   git/config
+    git/config
 '
 
 devel_files='
-   venvs/ve.conf
+    devel/venvs/ve.conf
 '
 
 remove_items=
 
 dirs_to_create="
-   $HOME/.cabal/bin
-   $HOME/.local/bin
-   $HOME/devel/node_lts
-   $HOME/devel/zig_nightly
+    $HOME/.cabal/bin
+    $HOME/.local/bin
+    $HOME/devel/node_lts
+    $HOME/devel/zig_nightly
 "
 
 items_to_clean="
-   $HOME/.cabal
+    $HOME/.cabal
 "
 
 items_to_nuke="
-   $HOME/catch
-   $HOME/devel/venvs
-   $HOME/devel/node_lts
-   $HOME/devel/zig_nightly
+    $HOME/catch
+    $HOME/devel/venvs
+    $HOME/devel/node_lts
+    $HOME/devel/zig_nightly
 "
 
 ## Perform ACTION
 
 case "$DF_ACTION" in
-   install|check|remove)
-      # Process Cabal configs for Haskell
-      process_files "$HOME/.cabal" "$cabal_files" cabal 0644
-      chmod 0755 "$HOME/.cabal"
+    install|check|remove)
+        # Process Cabal configs for Haskell
+        process_files "$HOME/.cabal" "$cabal_files" cabal 0644
+        chmod 0755 "$HOME/.cabal"
 
-      # Process miscellaneous ~/.config files
-      process_files "$XDG_CONFIG_HOME" "$dot_config_files" config 0644
+        # Process miscellaneous ~/.config files
+        process_files "$XDG_CONFIG_HOME" "$dot_config_files" config 0644
 
-      # Process devel files
-      process_files "$HOME/devel" "$devel_files" devel 0644
-      chmod 0755 "$HOME/devel"
+        # Process devel files
+        process_files "$HOME/devel" "$devel_files" devel 0644
+        chmod 0755 "$HOME/devel"
 
-      # Remove/report no longer needed files and directories
-      remove_items "$remove_items"
+        # Remove/report no longer needed files and directories
+        remove_items "$remove_items"
 
-      # Create/report missing/delete directories
-      ensure_dirs "$dirs_to_create"
-      ;;
-   clean)
-      remove_items "$items_to_clean"
-      ;;
-   nuke)
-      remove_items "$items_to_clean $items_to_nuke"
-      ;;
+        # Create/report missing/delete directories
+        ensure_dirs "$dirs_to_create"
+        ;;
+    clean)
+        remove_items "$items_to_clean"
+        ;;
+    nuke)
+        remove_items "$items_to_clean $items_to_nuke"
+        ;;
 esac
diff --git a/bin/dfInstall b/bin/dfInstall
--- a/bin/dfInstall
+++ b/bin/dfInstall
@@ -10,18 +10,18 @@
 #              --remove:  generally removes what was installed
 #              --clean:   like above but tries to conservatively clean things up
 #              --nuke:    like above but deletes even manually installed things
-#
-# shellcheck shell=dash
+
+# shellcheck shell=sh
 
 export DOTFILES_GIT_REPO="${DOTFILES_GIT_REPO:=$HOME/devel/dotfiles}"
-: "${df_home:=$DOTFILES_GIT_REPO/home}"
-: "${script_name:=dfInstall}"
+cd "$DOTFILES_GIT_REPO/home" || {
+    printf 'dfInstall: failed to cd into %s\n' "$DOTFILES_GIT_REPO/home" >&2
+    exit 1
+}
 
-cd "$df_home" || { printf '%s: failed to cd into %s\n' "$script_name" "$df_home"; }
+# Install in parallel - problematic when scripts converted to fish.
 
-export DF_ACTION=''
-. ../bin/sourced/setup.sh
-. ../bin/fishInstall
-. ../bin/bashInstall
-. ../bin/nvimInstall
-. ../bin/develInstall
+../bin/fishInstall  "$@"
+../bin/bashInstall  "$@"
+../bin/nvimInstall  "$@"
+../bin/develInstall "$@"
diff --git a/bin/fishInstall b/bin/fishInstall
--- a/bin/fishInstall
+++ b/bin/fishInstall
@@ -9,17 +9,38 @@
 #              --remove:  removes all files which were installed
 #              --clean:   same as above, deletes emptied directories
 #              --nuke:    removes everything fish related
-#
+
 # shellcheck shell=sh
-# shellcheck disable=SC3043
+
+export SCRIPT_NAME=fishInstall
+export DF_ACTION=install
 
 export DOTFILES_GIT_REPO="${DOTFILES_GIT_REPO:=$HOME/devel/dotfiles}"
-: "${df_home:=$DOTFILES_GIT_REPO/home}"
-: "${script_name:=fishInstall}"
+cd "$DOTFILES_GIT_REPO/home" || {
+    printf 'fishInstall: failed to cd into %s\n' "$DOTFILES_GIT_REPO/home" >&2
+    exit 1
+}
 
-cd "$df_home" || { printf '%s: failed to cd into %s\n' "$script_name" "$df_home"; }
+umask 0022
 
-. ../bin/sourced/setup.sh
+. ../bin/sourced/parse_cmdline.sh
+. ../bin/sourced/functions.sh
+
+# Script exclusively use these names
+export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:=$HOME/.config}"
+export XDG_CACHE_HOME="${XDG_CACHE_HOME:=$HOME/.cache}"
+export XDG_DATA_HOME="${XDG_DATA_HOME:=$HOME/.local/share}"
+export XDG_STATE_HOME="${XDG_STATE_HOME:=$HOME/.local/state}"
+
+# Ensure these folder exists before installation.
+ensure_dir "$XDG_CONFIG_HOME"
+chmod 0755 "$XDG_CONFIG_HOME"
+ensure_dir "$XDG_DATA_HOME"
+chmod 0755 "$XDG_DATA_HOME"
+ensure_dir "$XDG_STATE_HOME"
+chmod 0755 "$XDG_STATE_HOME"
+ensure_dir "$XDG_CACHE_HOME"
+chmod 0755 "$XDG_CACHE_HOME"
 
 config_files='
     completions/pp.fish
@@ -124,46 +145,44 @@ esac
 
 # Post ACTION Tasks
 
-case "$DF_ACTION" in
-    install)
-        # Ensure fish plugins are installed, assuming fish is.
-        if command -v fish >/dev/null 2>&1 && test "$DF_ACTION" = install
+test "$DF_ACTION" = install && {
+    # Ensure fish plugins are installed, assuming fish is.
+    if command -v fish >/dev/null 2>&1 && test "$DF_ACTION" = install
+    then
+        install_plugins=yes
+        if ! test -f "$XDG_CONFIG_HOME"/fish/functions/fisher.fish
         then
-            install_plugins=yes
-            if ! test -f "$XDG_CONFIG_HOME"/fish/functions/fisher.fish
+            # Just install fisher
+            rm -f "$XDG_CONFIG_HOME"/fish/fish_plugins
+            if ! fish -c df_install_fisher
             then
-                # Just install fisher
-                rm -f "$XDG_CONFIG_HOME"/fish/fish_plugins
-                if ! fish -c df_install_fisher
-                then
-                    printf '%s: Failed to install fisher\n' "$script_name" >&2
-                    install_plugins=no
-                fi
-            fi
-
-            if test "$install_plugins" = yes
-            then
-                fisher_list="$(fish -c 'fisher list')"
-                for plugin in $fish_plugins
-                do
-                    has_plugin=no
-
-                    for fisher_plugin in $fisher_list
-                    do
-                        if test "$plugin" = "$fisher_plugin"
-                        then
-                            has_plugin=yes
-                            break
-                        fi
-                    done
-
-                    if test "$has_plugin" = no
-                    then
-                        fish -c "fisher install $plugin"
-                            printf '%s: Failed to install fish plugins\n' "$script_name" >&2
-                    fi
-                done
+                printf '%s: Failed to install fisher\n' "$SCRIPT_NAME" >&2
+                install_plugins=no
             fi
         fi
-        ;;
-esac
+
+        if test "$install_plugins" = yes
+        then
+            fisher_list="$(fish -c 'fisher list')"
+            for plugin in $fish_plugins
+            do
+                has_plugin=no
+
+                for fisher_plugin in $fisher_list
+                do
+                    if test "$plugin" = "$fisher_plugin"
+                    then
+                        has_plugin=yes
+                        break
+                    fi
+                done
+
+                if test "$has_plugin" = no
+                then
+                    fish -c "fisher install $plugin"
+                        printf '%s: Failed to install fish plugins\n' "$SCRIPT_NAME" >&2
+                fi
+            done
+        fi
+    fi
+}
diff --git a/bin/nvimInstall b/bin/nvimInstall
--- a/bin/nvimInstall
+++ b/bin/nvimInstall
@@ -9,16 +9,38 @@
 #              --remove:  removes all files which were installed
 #              --clean:   same as above, but also lazy.nvim installation
 #              --nuke:    removes everything nvim related
-#
-# shellcheck shell=dash
+
+# shellcheck shell=sh
+
+export SCRIPT_NAME=nvimInstall
+export DF_ACTION=install
 
 export DOTFILES_GIT_REPO="${DOTFILES_GIT_REPO:=$HOME/devel/dotfiles}"
-: "${df_home:=$DOTFILES_GIT_REPO/home}"
-: "${script_name:=nvimInstall}"
+cd "$DOTFILES_GIT_REPO/home" || {
+    printf 'nvimInstall: failed to cd into %s\n' "$DOTFILES_GIT_REPO/home" >&2
+    exit 1
+}
 
-cd "$df_home" || { printf '%s: failed to cd into %s\n' "$script_name" "$df_home"; }
+umask 0022
 
-. ../bin/sourced/setup.sh
+. ../bin/sourced/parse_cmdline.sh
+. ../bin/sourced/functions.sh
+
+# Script exclusively use these names
+export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:=$HOME/.config}"
+export XDG_CACHE_HOME="${XDG_CACHE_HOME:=$HOME/.cache}"
+export XDG_DATA_HOME="${XDG_DATA_HOME:=$HOME/.local/share}"
+export XDG_STATE_HOME="${XDG_STATE_HOME:=$HOME/.local/state}"
+
+# Ensure these folder exists before installation.
+ensure_dir "$XDG_CONFIG_HOME"
+chmod 0755 "$XDG_CONFIG_HOME"
+ensure_dir "$XDG_DATA_HOME"
+chmod 0755 "$XDG_DATA_HOME"
+ensure_dir "$XDG_STATE_HOME"
+chmod 0755 "$XDG_STATE_HOME"
+ensure_dir "$XDG_CACHE_HOME"
+chmod 0755 "$XDG_CACHE_HOME"
 
 dot_config_files='
     after/ftplugin/c.lua
@@ -157,27 +179,26 @@ esac
 
 # Post ACTION Tasks
 
-case "$DF_ACTION" in
-    install)
-        # Recompiled spell file if necessary
-        if test "$compileSpellFile" = yes
-        then
-            sf="${SpellFile##*/}"
-            sf_dir="${SpellFile%/*}"
-            (
-                if cd "$sf_dir"
-                then
-                    nvim -u NONE --cmd "mkspell!$sf" --cmd 'qa!'
-                fi
-            )
-        fi
-        ;;
-    check)
-        # Indicate whether the spellfile will be recompiled on next install
-        if test "$compileSpellFile" = yes
-        then
-            printf 'nvimInstall: Spellfile "%s" will be\n' "$SpellFile"
-            printf '             recompiled on the next install.\n\n'
-        fi
-        ;;
-esac
+test "$DF_ACTION" = install && {
+    # Recompiled spell file if necessary
+    if test "$compileSpellFile" = yes
+    then
+        sf="${SpellFile##*/}"
+        sf_dir="${SpellFile%/*}"
+        (
+            if cd "$sf_dir"
+            then
+                nvim -u NONE --cmd "mkspell!$sf" --cmd 'qa!'
+            fi
+        )
+    fi
+}
+
+test "DF_ACTION" = check && {
+    # Indicate whether the spellfile will be recompiled on next install
+    if test "$compileSpellFile" = yes
+    then
+        printf 'nvimInstall: Spellfile "%s" will be\n' "$SpellFile" >&2
+        printf '             recompiled on the next install.\n\n' >&2
+    fi
+}
