Got instillation scripts working again.
- fisher working with install scripts
- started migrating bin/ensure_undercurl_terminfo.sh to fish
- removed SSH infrastructure, but
  - before I wired in the SSH service

    $ env|grep -i ssh
    SSH_AUTH_SOCK=/run/user/1000/gcr/ssh

diff --git a/bin/develInstall b/bin/develInstall
--- a/bin/develInstall
+++ b/bin/develInstall
@@ -1,11 +1,11 @@
 #!/bin/sh
 #
 # develInstall: Installs software development infrastructure and a basic
-#               fallback Bash environment into my home directory.
+#               fallback Bash environment into my $HOME directory.
 #
 # usage: develInstall [ --install | --check | --remove | --clean | --nuke ]
 #
-#        where --install: installs dotfiles into $HOME
+#        where --install: installs other development related config files
 #              --check:   checks what was installed
 #              --remove:  removes files which were installed
 #              --clean:   same as above, deletes emptied directories
@@ -14,21 +14,26 @@
 # shellcheck shell=dash
 #
 
-export scriptName=develInstall
-home="${DOTFILES_GIT_REPO:=~/devel/dotfiles}"/home
+scriptName=develInstall
+df_home="${DOTFILES_GIT_REPO:=~/devel/dotfiles}"/home
 
-cd "$home" 2>/dev/null || {
-   printf '\n%s: Error - failed to cd into "%s"\n\n' "$scriptName" "$home"
-   return 1
-}
+if test -d "$df_home"
+then
+    cd "$df_home" || {
+        printf '\n%s: Error - failed to cd into "%s"\n\n' "$scriptName" "$df_home"
+        exit 1
+    }
+else
+    printf '\n%s: Error - df_home = "%s" does not exist as a directory!\n\n' "$scriptName" "$df_home"
+    exit 1
+fi
 
-. ../bin/parse_cmdline_and_source_functions.sh
+. ../bin/sourced/parse_cmdline_and_source_functions.sh
 
 bash_files='
    .bash_profile
    .bashrc
    .inputrc
-   .profile
 '
 
 bin_scripts='
@@ -45,16 +50,13 @@ bin_scripts='
    viewJarManifest
 '
 
-bloop_files='
-   bloop.json
-'
-
 cabal_files='
    config
 '
 
 dot_config_files='
    git/config
+   systemd/user/ssh-agent.service
 '
 
 devel_files='
@@ -62,7 +64,7 @@ devel_files='
 '
 
 remove_items="
-   ~/.vimrc
+   ~/.vimrc\]
    ~/.bash_login
 "
 
@@ -74,12 +76,11 @@ dirs_to_create="
    $HOME/devel/zig_nightly
 "
 
-dirs_to_clean="
+items_to_clean="
    $HOME/.cabal
-   $HOME/.bloop
 "
 
-dirs_to_nuke="
+items_to_nuke="
    $HOME/catch
    $HOME/devel/venvs
    $HOME/devel/node_lts
@@ -96,10 +97,6 @@ case "$DF_ACTION" in
       # Process ~/bin scripts
       process_files "$HOME/bin" "$bin_scripts" bin 0755
       chmod 0755 "$HOME/bin"
-
-      # Process Bloop configs for Scala
-      process_files "$HOME/.bloop" "$bloop_files" bloop 0644
-      chmod 0755 "$HOME/.bloop"
 
       # Process Cabal configs for Haskell
       process_files "$HOME/.cabal" "$cabal_files" cabal 0644
@@ -119,9 +116,9 @@ case "$DF_ACTION" in
       ensure_dirs "$dirs_to_create"
       ;;
    clean)
-      remove_items "$dirs_to_clean"
+      remove_items "$items_to_clean"
       ;;
    nuke)
-      remove_items "$dirs_to_clean $dirs_to_nuke"
+      remove_items "$items_to_clean $items_to_nuke"
       ;;
 esac
diff --git a/bin/dfInstall b/bin/dfInstall
--- a/bin/dfInstall
+++ b/bin/dfInstall
@@ -1,7 +1,7 @@
 #!/bin/sh
 #
 # dfInstall: POSIX shell scripts to install an entire Linux desktop
-#            environment into a user's $HOME directory.
+#            environment into the user's $HOME directory.
 #
 # usage: dfInstall [ --install | --check | --remove | --clean | --nuke ]
 #
@@ -12,18 +12,24 @@
 #              --nuke:    like above but deletes even manually installed things
 #
 # shellcheck shell=dash
-#
 
-export scriptName=dfInstall
-home="${DOTFILES_GIT_REPO:=~/devel/dotfiles}"/home
+scriptName=dfInstall
+df_home="${DOTFILES_GIT_REPO:=$HOME/devel/dotfiles}"/home
 
-cd "$home" 2>/dev/null || {
-   printf '\n%s: Error - failed to cd into "%s"\n\n' "$scriptName" "$home"
-   return 1
-}
+if test -d "$df_home"
+then
+    cd "$df_home" || {
+        printf '\n%s: Error - failed to cd into "%s"\n\n' "$scriptName" "$df_home"
+        exit 1
+    }
+else
+    printf '\n%s: Error - df_home = "%s" does not exist as a directory!\n\n' "$scriptName" "$df_home"
+    exit 1
+fi
 
-export DF_ACTION=''
-. ../bin/parse_cmdline_and_source_functions.sh
+DF_ACTION=''
+
+. ../bin/sourced/parse_cmdline_and_source_functions.sh
 
 # Install dotfiles in parallel
 (. ../bin/nvimInstall) &
diff --git a/bin/fishInstall b/bin/fishInstall
--- a/bin/fishInstall
+++ b/bin/fishInstall
@@ -4,24 +4,30 @@
 #
 # usage: fishInstall [ --install | --check | --remove | --clean | --nuke ]
 #
-#        where --install: installs dotfiles into $HOME
+#        where --install: installs fish config into ~/.config/fish
 #              --check:   checks what was installed
-#              --remove:  removes files which were installed
+#              --remove:  removes all files which were installed
 #              --clean:   same as above, deletes emptied directories
-#              --nuke:    same as above but cleans up other content
+#              --nuke:    removes everything fish related
 #
-# shellcheck shell=dash
-#
+# shellcheck shell=sh
+# shellcheck disable=SC3043
 
-export scriptName=fishInstall
-home="${DOTFILES_GIT_REPO:=~/devel/dotfiles}"/home
+scriptName=fishInstall
+df_home="${DOTFILES_GIT_REPO:=~/devel/dotfiles}"/home
 
-cd "$home" 2>/dev/null || {
-    printf '\n%s: Error - failed to cd into "%s"\n\n' "$scriptName" "$home"
-    return 1
-}
+if test -d "$df_home"
+then
+    cd "$df_home" || {
+        printf '\n%s: Error - failed to cd into "%s"\n\n' "$scriptName" "$df_home"
+        exit 1
+    }
+else
+    printf '\n%s: Error - df_home = "%s" does not exist as a directory!\n\n' "$scriptName" "$df_home"
+    exit 1
+fi
 
-. ../bin/parse_cmdline_and_source_functions.sh
+. ../bin/sourced/parse_cmdline_and_source_functions.sh
 
 config_files='
     completions/pp.fish
@@ -96,38 +102,55 @@ remove_items="
 
 dirs_to_create=""
 
+items_to_clean="
+    $XDG_CONFIG_HOME/fish
+"
+
+items_to_nuke="
+    $XDG_CONFIG_HOME/fish
+    $XDG_DATA_HOME/fish
+    $XDG_CACHE_HOME/fish
+"
+
 ## Perform ACTION
 
 case "$DF_ACTION" in
     install|check|remove)
         # Install Fish config files
-        process_files "$XDG_CONFIG_HOME/fish" "$config_files" config/fish 0644 "$home"
+        process_files "$XDG_CONFIG_HOME/fish" "$config_files" config/fish 0644 "$df_home"
         chmod 0755 "$XDG_CONFIG_HOME/fish"
- 
-        # Ensure fish plugins are installed
-        if command -v fish >/dev/null 2>&1
-        then
-            if test -f "$XDG_CONFIG_HOME"/fish/functions/fisher.fish || fish -c _df_install_fisher
-            then
-                errmsg='%s: Failed to install fish plugins\n'
-                { fish -c 'fisher update'; } || printf "$errmsg" "$scriptName"
-            else
-                printf '%s: Failed to install fisher\n' "$scriptName"
-            fi
-        fi
 
         # Remove/report no longer needed files and directories
         remove_items "$remove_items"
  
         # Create/report missing directories
         ensure_dirs "$dirs_to_create"
+ 
+        # Ensure fish plugins are installed, assuming fish is.
+        if command -v fish >/dev/null 2>&1 && test "$DF_ACTION" = install
+        then
+            install_plugins=yes
+            if ! test -f "$XDG_CONFIG_HOME"/fish/functions/fisher.fish
+            then
+                if ! fish -c df_install_fisher
+                then
+                    printf '%s: Failed to install fisher\n' "$scriptName" >&2
+                    install_plugins=no
+                fi
+            fi
+            if test "$install_plugins" = yes
+            then
+                if fish -c 'fisher update'
+                then
+                    printf '%s: Failed to install fish plugins\n' "$scriptName"
+                fi
+            fi
+        fi
         ;;
     clean)
-        remove_items "$XDG_CONFIG_HOME/fish"
-        ;;
+       remove_items "$items_to_clean"
+       ;;
     nuke)
-        remove_items "$XDG_CONFIG_HOME/fish"
-        remove_items "$XDG_DATA_HOME/fish"
-        remove_items "$XDG_CACHE_HOME/fish"
-        ;;
+       remove_items "$items_to_clean $items_to_nuke"
+       ;;
 esac
diff --git a/bin/nvimInstall b/bin/nvimInstall
--- a/bin/nvimInstall
+++ b/bin/nvimInstall
@@ -13,15 +13,21 @@
 # shellcheck shell=dash
 #
 
-export scriptName=nvimInstall
-home="${DOTFILES_GIT_REPO:=~/devel/dotfiles}"/home
+scriptName=nvimInstall
+df_home="${DOTFILES_GIT_REPO:=~/devel/dotfiles}"/home
 
-cd "$home" 2>/dev/null || {
-    printf '\n%s: Error - failed to cd into "%s"\n\n' "$scriptName" "$home"
-    return 1
-}
+if test -d "$df_home"
+then
+    cd "$df_home" || {
+        printf '\n%s: Error - failed to cd into "%s"\n\n' "$scriptName" "$df_home"
+        exit 1
+    }
+else
+    printf '\n%s: Error - df_home = "%s" does not exist as a directory!\n\n' "$scriptName" "$df_home"
+    exit 1
+fi
 
-. ../bin/parse_cmdline_and_source_functions.sh
+. ../bin/sourced/parse_cmdline_and_source_functions.sh
 
 dot_config_files='
     after/ftplugin/c.lua
@@ -134,7 +140,7 @@ case "$DF_ACTION" in
         process_files "$XDG_CONFIG_HOME/nvim" "
             $dot_config_files
             $toml_files
-        " config/nvim 0644 "$home"
+        " config/nvim 0644 "$df_home"
         chmod 0755 "$XDG_CONFIG_HOME/nvim"
  
         # Remove/report no longer needed files and directories
