Finished wiring together dotfiles install scripts
- every thing contained in a single repo
  - 4 independent $HOME install scripts
    - fishInstall with fInstall fish abbr
    - nvimInstall with nvInstall fish abbr
    - swayInstall with swInstall fish abbr
    - homeInstall with hInstall fish abbr
    - dfInstall to fire all four at once
    - abbreviations can be launched from any direcrory
  - 1 system /etc install script (Arch Linux Only!)
    - sfInstall with sfInstall fish abbr
    - removed my exeriments with ip6 networking
    - trying out new console font: Lat3-Terminus16
      - previously recommended on Arch Wiki in setup guides
    - NOT TESTED YET

diff --git a/bin/dfInstall b/bin/dfInstall
--- a/bin/dfInstall
+++ b/bin/dfInstall
@@ -1,88 +1,32 @@
 #!/bin/sh
 #
-# POSIX shell script to install an entire Linix desktop environment
+# POSIX shell script to install an entire Linux desktop environment
 # into the $HOME directory.
-#
-# shellcheck disable=SC2031
-#   SC2031: "var" was modified in a subshell (reason why a subshell was used!)
 #
 # Tested with both dash and bash.
 #
 
-me="$(id -un)"
+scriptName=dfInstall
+gitRepo="${DOTFILE_GIT_REPO:=$HOME/devel/dotfiles}"
 
-export MyRepoName=dotfiles
-export MyScriptName=dfInstall
-
-XDG_CONFIG_HOME="${XDG_CONFIG_HOME:=$HOME/.config}"
-GIT_REPO="${DOTFILE_GIT_REPO:=$HOME/devel/dotfiles}"
-umask 0022
-
-cd "$GIT_REPO" || {
-   printf '\n%s: Error - failed to cd into "%s"\n' "$MyScriptName" "$GIT_REPO"
+cd "$gitRepo" || {
+   printf '\n%s: Error - failed to cd into "%s"\n' "$scriptName" "$gitRepo"
    return 1
 }
 
-
 ## Parse cmdline arguments and source functions
 switch=''
-. ./.installSource.sh
+. bin/.setup.sh
 
-## Installation configuration
-
-if test "$me" = grs
-then
-   df_Config_Files_grs='
-      git/config
-   '
-   df_Remove_Items_grs=''
-else
-   df_Config_Files_grs=''
-   df_Remove_Items_grs=''
-fi
-df_Config_Files='
-   nixpkgs/config.nix
-'
-df_Remove_Items=''
-df_Dirs_To_Create=''
-
-## Install/Check
-
+## Install dotfiles
 ensure_dir "$XDG_CONFIG_HOME"
 chmod 0755 "$XDG_CONFIG_HOME"
 
-# Install git submodules boldly in parallel in subshells
-# with a single instance of sh (tested with Dash and Bash).
-FISH_GIT_REPO="${GIT_REPO}/config/fish"
-NVIM_GIT_REPO="${GIT_REPO}/config/nvim"
-HOME_GIT_REPO="${GIT_REPO}/home"
-SWAY_GIT_REPO="${GIT_REPO}/sway-env"
-( . ./config/fish/fishInstall ) &
-( . ./config/nvim/nvInstall ) &
-( . ./home/homeInstall ) &
-( . ./sway-env/swayInstall ) &
+# Boldly install configuration files in parallel
+( . fish-env/fishInstall ) &
+( . nvim-env/nvimInstall ) &
+( . home-env/homeInstall ) &
+( . sway-env/swayInstall ) &
 
-# Install miscellaneous $XDG_CONFIG_HOME configuration files
-install_files "$XDG_CONFIG_HOME" "$df_Config_Files_grs $df_Config_Files" ./config 0644
-
-# Remove/report no longer needed files and directories
-remove_items "$df_Remove_Items_grs $df_Remove_Items"
-
-# Create/report missing directories
-ensure_dirs "$df_Dirs_To_Create"
-
-# Adjustments/tweaks/tasks
-case "$switch" in
-   install)
-      :
-      ;;
-   repo)
-      git_status
-      ;;
-   check)
-      :
-      ;;
-esac
-
-# Make sure all background jobs to finish
+# Make sure all background jobs finish
 wait
diff --git a/fish-env/fishInstall b/fish-env/fishInstall
--- a/fish-env/fishInstall
+++ b/fish-env/fishInstall
@@ -4,22 +4,21 @@
 #
 #
 
-export MyRepoName=fish
-export MyScriptName=fishInstall
+scriptName=fishInstall
+envName=fish-env
 
-XDG_CONFIG_HOME="${XDG_CONFIG_HOME:=$HOME/.config}"
-GIT_REPO="${FISH_GIT_REPO:=$HOME/devel/dotfiles-submodules/fish}"
-umask 0022
+gitRepo="${DOTFILE_GIT_REPO:=$HOME/devel/dotfiles}"
+envPath="$gitRepo/$envName"
 
-cd "$GIT_REPO" || {
-   printf '\n%s: Error - failed to cd into "%s"\n' "$MyScriptName" "$GIT_REPO"
+cd "$envPath" || {
+   printf '%s: Error - failed to cd into "%s"\n\n' "$scriptName" "$envPath"
    return 1
 }
 
 ## Source install infrastructure and, if not done already, parse cmdline args
-. ./.installSource.sh
+. "$gitRepo/bin/.setup.sh"
 
-fish_Config_Files='
+fish_config_files='
    completions/alacritty.fish
    completions/pypi.fish
    completions/ve.fish
@@ -79,31 +78,28 @@ fish_Config_Files='
    functions/ud.fish
 '
 
-fish_Remove_Items="
+fish_remove_items="
    $XDG_CONFIG_HOME/fish/functions/fishterm.fish
 "
 
-DIRS_TO_CREATE=""
+dirs_to_create=""
 
 ## Install/Check
 
 # Install Fish config files
-install_files "$XDG_CONFIG_HOME/fish" "$fish_Config_Files" . 0644
+install_files "$XDG_CONFIG_HOME/fish" "$fish_config_files" config/fish 0644 "$envPath"
 chmod 0755 "$XDG_CONFIG_HOME/fish"
 
 # Remove/report no longer needed files and directories
-remove_items "$fish_Remove_Items"
+remove_items "$fish_remove_items"
 
 # Create/report missing directories
-ensure_dirs "$DIRS_TO_CREATE"
+ensure_dirs "$dirs_to_create"
 
 # Adjustments/tweaks/tasks
 case "$switch" in
    install)
       :
-      ;;
-   repo)
-      git_status
       ;;
    check)
       :
diff --git a/home-env/homeInstall b/home-env/homeInstall
--- a/home-env/homeInstall
+++ b/home-env/homeInstall
@@ -1,36 +1,37 @@
 #!/bin/sh
 #
-#  Installs my Bash environment and other configurations into $HOME directory.
+#  Installs a basic Bash environment and other home
+#  directory miscellaneous configurations and tweaks.
 #
-#    - bash (startup files)
-#    - ~/bin scripts for various scipting languages
-#    - ssh, bloop (Scala), Cabal (Haskell)
-#    - create directories important to my work flow
-#    - remove items
+#  - bash (startup files)
+#  - ~/bin scripts
+#  - ssh
+#  - bloop (Scala), Cabal (Haskell)
+#  - create directories important to my work flow
+#  - remove items
 #
 
-export MyRepoName=home
-export MyScriptName=homeInstall
+scriptName=homeInstall
+envName=home-env
 
-XDG_CONFIG_HOME="${XDG_CONFIG_HOME:=$HOME/.config}"
-GIT_REPO="${HOME_GIT_REPO:=$HOME/devel/dotfiles-submodules/home}"
-umask 0022
+gitRepo="${DOTFILE_GIT_REPO:=$HOME/devel/dotfiles}"
+envPath="$gitRepo/$envName"
 
-cd "$HOME_GIT_REPO" || {
-   printf '\nError - failed to cd into "%s"\n' "$MyScriptName" "$GIT_REPO"
+cd "$envPath" || {
+   printf 'Error %s: failed to cd into "%s"\n\n' "$scriptName" "$envPath"
    return 1
 }
 
-## source install infrastructure and, if not done already, parse cmdline args
-. ./.installSource.sh
+## Parse cmdline arguments and source functions, if not done already
+. "$gitRepo/bin/.setup.sh"
 
-home_Files='
+home_files='
    .bash_profile
    .bashrc
    .inputrc
 '
 
-home_Bin_Scripts='
+home_bin_scripts='
    buArch
    chkcolor
    codepoint
@@ -44,23 +45,27 @@ home_Bin_Scripts='
    viewJarManifest
 '
 
-home_Ssh_Files='
-   config
-'
-
-home_Bloop_Files='
+home_bloop_files='
    bloop.json
 '
 
-home_Cabal_Files='
+home_cabal_files='
    config
 '
 
-home_Remove_Items="
+home_config_files='
+   git/config
+   nixpkgs/config.nix
+'
+home_remove_items="
    $HOME/.vimrc
 "
 
-home_Dirs_To_Create="
+home_ssh_files='
+   config
+'
+
+home_ensure_dirs_exist="
    $HOME/catch
    $HOME/.local/bin
    $HOME/.cabal/bin
@@ -69,37 +74,38 @@ home_Dirs_To_Create="
 ## Install or Check
 
 # Install bash config files
-install_files "$HOME" "$home_Files" . 0644
+install_files "$HOME" "$home_files" . 0644 "$envPath"
 
 # Install ~/bin scripts
-install_files "$HOME/bin" "$home_Bin_Scripts" ./bin 0755
+install_files "$HOME/bin" "$home_bin_scripts" bin 0755 "$envPath"
 chmod 0755 "$HOME/bin"
 
-# Install SSH Configs
-install_files "$HOME/.ssh" "$home_Ssh_Files" ./ssh 0600
+# Install ssh configs
+install_files "$HOME/.ssh" "$home_ssh_files" ssh 0600 "$envPath"
 chmod 0700 "$HOME/.ssh"
 
-# Install Bloop Configs for Scala
-install_files "$HOME/.bloop" "$home_Bloop_Files" ./bloop 0644
+# Install Bloop configs for Scala
+install_files "$HOME/.bloop" "$home_bloop_files" bloop 0644 "$envPath"
 chmod 0755 "$HOME/.bloop"
 
-# Install Cabal Configs for Haskell
-install_files "$HOME/.cabal" "$home_Cabal_Files" ./cabal 0644
+# Install Cabal configs for Haskell
+install_files "$HOME/.cabal" "$home_cabal_files" cabal 0644 "$envPath"
+chmod 0755 "$HOME/.cabal"
+
+# Install miscellaneous ~/.config files
+install_files "$HOME/.config" "$home_config_files" config 0644 "$envPath"
 chmod 0755 "$HOME/.cabal"
 
 # Remove/report no longer needed files and directories
-remove_items "$home_Remove_Items"
+remove_items "$home_remove_items"
 
 # Create/report missing directories
-ensure_dirs "$home_Dirs_To_Create"
+ensure_dirs "$home_ensure_dirs_exist"
 
 ## Adjustments/tweaks/tasks
 case "$switch" in
    install)
       :
-      ;;
-   repo)
-      git_status
       ;;
    check)
       :
diff --git a/nvim-env/nvimInstall b/nvim-env/nvimInstall
--- a/nvim-env/nvimInstall
+++ b/nvim-env/nvimInstall
@@ -3,22 +3,21 @@
 #  Installs my Neovim environment into my $HOME directory.
 #
 
-export MyRepoName=nvim
-export MyScriptName=nvInstall
+scriptName=nvimInstall
+envName=nvim-env
 
-XDG_CONFIG_HOME="${XDG_CONFIG_HOME:=$HOME/.config}"
-GIT_REPO="${NVIM_GIT_REPO:=$HOME/devel/dotfiles-submodules/nvim}"
-umask 0022
+gitRepo="${DOTFILE_GIT_REPO:=$HOME/devel/dotfiles}"
+envPath="$gitRepo/$envName"
 
-cd "$GIT_REPO" || {
-   printf '\n%s: Error - Failed to cd into "%s"\n' "$MyScriptName" "$GIT_REPO"
+cd "$envPath" || {
+   printf '%s: Error - Failed to cd into "%s"\n\n' "$scriptName" "$envPath"
    return 1
 }
 
-## source install infrastructure and, if not done already, parse cmdline args
-. ./.installSource.sh
+## Parse cmdline arguments and source functions, if not done already
+. "$gitRepo/bin/.setup.sh"
 
-nv_Config_Files='
+nv_config_files='
    ftplugin/c.lua
    ftplugin/cpp.lua
    ftplugin/csv.lua
@@ -65,53 +64,42 @@ nv_Config_Files='
    init.lua
 '
 
-nv_Toml_Files='
+nv_toml_files='
    selene.toml
    stylua.toml
    vim.toml
 '
 
-nv_Remove_Items="
-   $XDG_CONFIG_HOME/nvim/lua/grs/plugins/linters.lua
-"
+nv_remove_items=""
 
-nv_Dirs_To_Create=""
+nv_dirs_to_create=""
 
 ## Install/Check
 
 # Install Neovim files & NVIM related TOML files
 install_files "$XDG_CONFIG_HOME/nvim" "
-   $nv_Config_Files
-   $nv_Toml_Files
-" . 0644
+   $nv_config_files
+   $nv_toml_files
+" config/nvim 0644 "$envPath"
 chmod 0755 "$XDG_CONFIG_HOME/nvim"
 
-# Remove/report no longer needed files and directories
-remove_items "$nv_Remove_Items"
+# Remove/report no longer needed files and directories thru
+remove_items "$nv_remove_items"
 
 # Create/report missing directories
-ensure_dirs "$nv_Dirs_To_Create"
+ensure_dirs "$nv_dirs_to_create"
 
 # Adjustments/tweaks/tasks
 case "$switch" in
    install)
-      printf '{}' > "$XDG_CONFIG_HOME/nvim/.neoconf.json"
-      ;;
-   repo)
-      git_status
+      printf '{}' > "$XDG_CONFIG_HOME"/nvim/.neoconf.json
       ;;
    check)
       SpellFile="$XDG_CONFIG_HOME/nvim/spell/en.utf-8.add"
-      if test -f "$SpellFile"
+      if ! test -e "$SpellFile" || ! diff -q "$SpellFile" config/nvim/spell/en.utf-8.add 2>/dev/null
       then
-         if ! diff -q spell/en.utf-8.add "$SpellFile" > /dev/null
-         then
-            printf "Spell file: %s will need updating/compiling:\n" "$SpellFile"
-            printf "   After install,\n"
-            printf "      $ cd %s\n" "${SpellFile%/*}/"
-            printf "      $ nvim %s\n" "${SpellFile##*/}"
-            printf "      :mkspell! %s\n\n" "${SpellFile##*/}"
-         fi
+         printf '\nThe spell file %s will need to be compiled after the install:\n\n' "$SpellFile"
+         printf "  $ cd %s; nvim -c ':mkspell! %%' -c 'q' %s; cd -\n\n" "${SpellFile%/*}/" "${SpellFile##*/}"
       fi
       ;;
 esac
diff --git a/sway-env/swayInstall b/sway-env/swayInstall
--- a/sway-env/swayInstall
+++ b/sway-env/swayInstall
@@ -8,26 +8,32 @@
 #    mpd - Music daemon for linux
 #
 
-export MyRepoName=sway-env
-export MyScriptName=swayInstall
+scriptName=swayInstall
+envName=sway-env
 
-XDG_CONFIG_HOME="${XDG_CONFIG_HOME:=$HOME/.config}"
-XDG_STATE_HOME="${XDG_STATE_HOME:=$HOME/.local/state}"
-XDG_CACHE_HOME="${XDG_CACHE_HOME:=$HOME/.cache}"
-GIT_REPO="${SWAY_GIT_REPO:=$HOME/devel/dotfiles-submodule/sway-env}"
-umask 0022
+gitRepo="${DOTFILE_GIT_REPO:=$HOME/devel/dotfiles}"
+envPath="$gitRepo/$envName"
 
-cd "$GIT_REPO" || {
-   printf '\n%s: Error - failed to cd into "%s"\n' "$MyScriptName" "$GIT_REPO"
+cd "$envPath" || {
+   printf '%s: Error - failed to cd into "%s"\n\n' "$scriptName" "$envPath"
    return 1
 }
 
-## source install infrastructure and, if not done already, parse cmdline args
-. ./.installSource.sh
+## Parse cmdline arguments and source functions, if not done already
+. "$gitRepo/bin/.setup.sh"
+
+XDG_STATE_HOME="${XDG_STATE_HOME:=$HOME/.local/state}"
+XDG_CACHE_HOME="${XDG_CACHE_HOME:=$HOME/.cache}"
 
 ## Files to install
 
-sway_Config_Files='
+sway_config_files='
+   config
+   config_bg_color
+   config_bg_picture
+'
+
+sway_related_files='
    alacritty/alacritty_arch.toml
    alacritty/alacritty.toml
    alacritty/alacritty_arch.yml
@@ -35,32 +41,29 @@ sway_Config_Files='
    kanshi/config
    mako/config
    mpd/mpd.conf
-   sway/config
-   sway/config_bg_color
-   sway/config_bg_picture
    waybar/config
    waybar/style.css
    wofi/config
    wofi/style.css
 '
 
-sway_Systemd_Service_Files='
-   systemd/user/kanshi.service
-   systemd/user/mako.service
-   systemd/user/sway-session.target
+sway_systemd_service_files='
+   kanshi.service
+   mako.service
+   sway-session.target
 '
 
-sway_Bin_Scripts='
+sway_bin_scripts='
    startw
 '
 
-sway_Remove_Items="
+sway_remove_items="
    $HOME/.mako
    $HOME/.mpd
    $HOME/.sway
 "
 
-sway_Dirs_To_Create="
+sway_dirs_to_create="
    $XDG_CONFIG_HOME/mpd/playlists
    $XDG_STATE_HOME/mpd/
    $XDG_CACHE_HOME/mpd/
@@ -68,21 +71,24 @@ sway_Dirs_To_Create="
 
 ## Install or Check
 
-# Install Sway and Sway/Desktop related config files
-install_files "$XDG_CONFIG_HOME" "
-   $sway_Config_Files
-   $sway_Systemd_Service_Files
-" ./config 0644
+# Install Sway config files
+install_files "$XDG_CONFIG_HOME/sway" "$sway_config_files" config/sway 0644 "$envPath"
+
+# Install Sway desktop related config files
+install_files "$XDG_CONFIG_HOME" "$sway_related_files" config 0644 "$envPath"
+
+# Install Sway related Systemd service files
+install_files "$XDG_CONFIG_HOME/systemd/user" "$sway_systemd_service_files" config/systemd/user 0644 "$envPath"
 
 # Install ~/bin scripts
-install_files "$HOME/bin" "$sway_Bin_Scripts" ./bin 0755
+install_files "$HOME/bin" "$sway_bin_scripts" bin 0755 "$envPath"
 chmod 0755 "$HOME/bin"
 
 # Remove/report no longer needed files and directories
-remove_items "$sway_Remove_Items"
+remove_items "$sway_remove_items"
 
 # Create/report missing directories
-ensure_dirs "$sway_Dirs_To_Create"
+ensure_dirs "$sway_dirs_to_create"
 
 # Adjustments/tweaks/tasks
 case "$switch" in
@@ -103,9 +109,6 @@ case "$switch" in
       # Reload Systemd user services in case config files get updated
       systemctl --user daemon-reload
       :
-      ;;
-   repo)
-      git_status
       ;;
    check)
       :
